language: node_js
node_js: 7
script:
- gulp && npm test
deploy:
  provider: heroku
  api_key:
    secure: iBJ75smvz9dkOTtZ3IB9fjeWfVOB06zpNpzqEnlyXz9GuwHKCmFDRomKJzNZUpX0TFGlo6w/y2F3UevjGA6d/jT8oayeVc7TjUGjIdrYtEtc5STRKi5vfzb9gYJHYbEdmpy0TDRVLE+4CkUm3tPkRwX8G/nOtzVYO5D8IJZCtfS4UymI5a8N13jIMOK8AM2N7xNvQ/7tDPzoQ1r4yT+sDHbuQxTDiPZTwknOaBbducWgiclmDXC8P4F8VvSu32jn7MW+Bu0PSUnG9LgQCGoXrP9wDstpuUmpWD9BDjDmqzC5xAE1WJ65vl/PTQ9OkAhGje6zYhs50MCwOEZ/85FHKtMvHzvNmDReAfkFo9is7MQTWb8z1MIHRuyJJKlBVqKjMh9yYAgvWxRG1Z8L+jUjsQkYqWyJdhWBXRj+4b84NTNWkCRiQSo3abenIM4aCBfam+UG+gbUhpm23vAGFnR/UAS0LOz/93hqjgY5fpPlKLD89PAfSwc4CQ8wqMuoR6DMOIk2aKfIv8KljDyCK3ngAzn5Cioac2x6ht3fq4vJddjm8LCtCtxmJtMY/Tl0Me7vSaJOeSYLucnqwmH6++EZeUNaEYMpAIQQSKwcxuIJk618mKJ1BAyg0TuflVGfx+svou/rMtTcW1TAAE3l/SwRFqnPLtPUJkn9uZu5wcTThjw=
  app: stormy-wave-24728
  on:
    repo: karimsa/delish
